seed: 42
output_dir: "experiments"
data:
  data_root: "./data"
  val_size: 0.2
  use_class_weights: true
  normalize: true

model:
  name: "cnn"
  input_size: [128, 128]
  num_classes: 3

parameters:
  epochs: 80
  batch_size: 64
  lr: 1e-3
  weight_decay: 1e-4
  milestones: [45, 65]
  lr_decay: 0.1
  early_stopping: 12
  report_interval: 1
  warmup: 3
  # if using focal, you can optionally supply alpha per-class
  # otherwise the training will use class weights
  loss_type: "focal"
  alpha: [0.33, 0.33, 0.34]
  lambda_DA: 0.005
  # or you can use cross entropy
  # loss_type: "cross_entropy"